from django.conf.urls import patterns, include, url

from recogmatch import views as match_views

urlpatterns = patterns('',
    url(r'^(?P<username>[\.\w]+)/(?P<challenge_id>[\d]+)/submit/$',
        match_views.submit_raw_data,
        name='match_submit'),
    url(r'^(?P<username>[\.\w]+)/train/(?P<challenge>[\-\w]+)/$',
        match_views.challenge,
        {'template_name': 'recogmatch/challenge_template.html',
         'model_action': 'train'},
        name='match_train_item'),
    url(r'^(?P<username>[\.\w]+)/train/$',
        match_views.challenge,
        {'model_action': 'train'},
        name='match_train_list'),
    url(r'^(?P<username>[\.\w]+)/challenge/(?P<challenge>[\-\w]+)/$',
        match_views.challenge,
        {'template_name': 'recogmatch/challenge_template.html',
         'model_action': 'challenge'},
        name='match_challenge_item'),
    url(r'^(?P<username>[\.\w]+)/challenge/$',
        match_views.challenge,
        {'model_action': 'challenge'},
        name='match_challenge_list'),
    url(r'^(?P<username>[\.\w]+)/(?P<result_mod>[0-9\&]+)/$', 
        match_views.guide_user,
        name='guide_user'),
    url(r'^(?P<username>[\.\w]+)/$', 
        match_views.guide_user,
        name='guide_user'),
)
